FROM ubuntu-ros-noetic:20.04

COPY turtlebot3_burger_for_velodyne3D.urdf.xacro turtlebot3_waffle_for_velodyne3D.urdf.xacro /home/suchetan/ros_ws/src/turtlebot3/turtlebot3_description/urdf/
COPY turtlebot3_velodyne3D.launch /home/suchetan/ros_ws/src/turtlebot3_simulations/turtlebot3_gazebo/launch/